site_name: Benchmarks
site_description: Benchmarks
site_author: mestarz
site_url: https://mestarz.github.io/
repo_name: mestarz/mestarz-benchmarks
repo_url: https://github.com/mestarz/mestarz-benchmarks
copyright: Copyright &copy; 2020-2021 mestarz
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: ./static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- 介绍:
  - index.md
  - introduce.md
- 神经网络模型:
  - Model/LeNet.md
  - Model/AlexNet.md
  - Model/ZFNet.md
  - Model/Vgg16.md
  - Model/GoogleNet.md
  - Model/InceptionV2.md
  - Model/InceptionV3.md
  - Model/InceptionV4.md
  - Model/ResNet50.md
  - Model/ResNet101.md
  - Model/ResNet152.md
  - Model/DeseNet121.md
  - Model/MobileNetv2.md
  - Model/ShuffleNetv2.md
  - Model/SqueezeNetv1.1.md
  - Model/R-CNN.md
  - Model/YOLOV3.md
  - Model/FCN.md
  - Model/U-Net.md
- 跟踪算子:
  - Tracker/BOOSTING_Tracker.md
  - Tracker/MIL_Tracker.md
  - Tracker/KCF_Tracker.md
  - Tracker/CSRT_Tracker.md
  - Tracker/MedianFlow_Tracker.md
  - Tracker/TLD_Tracker.md
  - Tracker/MOSSE_Tracker.md
  - Tracker/GOTURN_Tracker.md
- 强化学习方法:
  - Reinforcement/Q-Learning.md
  - Reinforcement/SARSA.md
  - Reinforcement/DQN.md
  - Reinforcement/PG.md
  - Reinforcement/DDPG.md
  - Reinforcement/PPO.md
  
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
