site_name: Benchmarks
site_description: Benchmarks
site_author: mestarz
site_url: https://mestarz.github.io/
repo_name: mestarz/mestarz-benchmarks
repo_url: https://github.com/mestarz/mestarz-benchmarks
copyright: Copyright &copy; 2020-2021 mestarz
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: ./static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- 介绍:
  - index.md
  
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
